In [1]:
import numpy as np

d=np.array(5)
print(d.ndim)
print(d.shape)
#0차원 텐서

0
()


In [2]:
d=np.array([1,2,3,4])
print(d.ndim)
print(d.shape)
#1차원 텐서

1
(4,)


In [5]:
d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d.ndim)
print(d.shape)
#2차원 텐서

2
(3, 4)


In [8]:
d=np.array([
    [[1,2,3,4,5],[6,7,8,9,10],[10,11,12,13,14]],
    [[15,16,17,18,19],[19,20,21,22,23],[23,24,25,26,27]]
            ])
print(d.ndim)
print(d.shape)
#3차원 텐서

3
(2, 3, 5)


In [9]:
a = np.array([8, 4, 5])
b = np.array([1, 2, 3])
print(a+b)
print(a-b)

[9 6 8]
[7 2 2]


In [10]:
import numpy as np
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
b = np.array([[5, 6, 7, 8],[1, 2, 3, 4]])
print(a+b)
print(a-b)

[[15 26 37 48]
 [51 62 73 84]]
[[ 5 14 23 32]
 [49 58 67 76]]


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a,b))

32
