In [3]:
import numpy as np
A=np.array([[0,0,0,1,0,1,1,0,0],[0,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,0,0],[1,0,0,0,0,0,0,1,1]])
np.shape(A)

(4, 9)

In [4]:
U, s, VT = np.linalg.svd(A, full_matrices=True)
print(U.round(2))
np.shape(U)

[[ 0.24  0.75  0.    0.62]
 [ 0.51  0.44 -0.   -0.74]
 [ 0.83 -0.49 -0.    0.27]
 [ 0.   -0.    1.   -0.  ]]


(4, 4)

In [5]:
print(s.round(2))
np.shape(s)

[2.69 2.05 1.73 0.77]


(4,)

In [7]:
S = np.zeros((4,9))
S[:4, :4] = np.diag(s)
print(S.round(2))
np.shape(S)

[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]


(4, 9)

In [9]:
print(VT.round(2))
np.shape(VT)

[[ 0.    0.31  0.31  0.28  0.8   0.09  0.28  0.    0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [-0.    0.35  0.35 -0.16 -0.25  0.8  -0.16  0.    0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]


(9, 9)

In [10]:
np.allclose(A, np.dot(np.dot(U,S), VT).round(2))

True

In [11]:
S=S[:2,:2]
print(S.round(2))

[[2.69 0.  ]
 [0.   2.05]]


In [12]:
U=U[:,:2]
print(U.round(2))
# 문서의 개수 x 토픽의 수 t의 크기

[[ 0.24  0.75]
 [ 0.51  0.44]
 [ 0.83 -0.49]
 [ 0.   -0.  ]]


In [13]:
VT=VT[:2,:]
print(VT.round(2))
# 토픽의 수 x 단어의 개수의 크기

[[ 0.    0.31  0.31  0.28  0.8   0.09  0.28  0.    0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]


In [14]:
A_prime = np.dot(np.dot(U,S), VT)
print(A)
print(A_prime.round(2))

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]


In [15]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
documents = dataset.data
len(documents)

11314

In [16]:
documents[1]

"\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n\n\n\n\n\n\nJim,\n\nSorry I can't pity you, Jim.  And I'm sorry that you have these feelings of\ndenial about the faith you need to get by.  Oh well, just pretend that it will\nall end happily ever after anyway.  Maybe if you start a new newsgroup,\nalt.atheist.hard, you won't be bummin' so much?\n\n\n\n\n\n\nBye-Bye, Big Jim.  Don't forget your Flintstone's Chewables!  :) \n--\nBake Timmons, III"

In [17]:
print(dataset.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [25]:
# 텍스트 전처리
news_df = pd.DataFrame({'document':documents})
#특수 문자 제거
news_df['clean_doc'] = news_df['document'].str.replace("[^a-z,A-Z]"," ")
# 길이가 3이하인 단어 제거
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x : ' '.join([w for w in x.split() if len(w) > 3]))
# 전체 단어에 대한 소문자 변환
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x : x.lower())

In [22]:
news_df['clean_doc'][1]

'yeah, expect people read faq, actually accept hard atheism need little leap faith, jimmy your logic runs steam jim, sorry pity you, sorry that have these feelings denial about faith need well, just pretend that will happily ever after anyway maybe start newsgroup, atheist hard, bummin much bye, forget your flintstone chewables bake timmons,'

In [26]:
# 불용어 제거
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
tokenized_doc = news_df['clean_doc'].apply(lambda x: x.split()) #토큰화
tokenized_doc = tokenized_doc.apply(lambda x: [item for item in x if item not in stop_words])
# 불용어 제거

In [27]:
print(tokenized_doc[1])

['yeah,', 'expect', 'people', 'read', 'faq,', 'actually', 'accept', 'hard', 'atheism', 'need', 'little', 'leap', 'faith,', 'jimmy', 'logic', 'runs', 'steam', 'jim,', 'sorry', 'pity', 'you,', 'sorry', 'feelings', 'denial', 'faith', 'need', 'well,', 'pretend', 'happily', 'ever', 'anyway', 'maybe', 'start', 'newsgroup,', 'atheist', 'hard,', 'bummin', 'much', 'bye,', 'forget', 'flintstone', 'chewables', 'bake', 'timmons,']


In [28]:
# TF-IDF 행렬 만들기
# 역토큰화
detokenized_doc = []
for i in range(len(news_df)):
    t = ' '.join(tokenized_doc[i])
    detokenized_doc.append(t)
    
news_df['clean_doc'] = detokenized_doc

In [29]:
news_df['clean_doc'][1]

'yeah, expect people read faq, actually accept hard atheism need little leap faith, jimmy logic runs steam jim, sorry pity you, sorry feelings denial faith need well, pretend happily ever anyway maybe start newsgroup, atheist hard, bummin much bye, forget flintstone chewables bake timmons,'

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english', max_features=1000, max_df=0.5, smooth_idf=-True)

X = vectorizer.fit_transform(news_df['clean_doc'])
X.shape

(11314, 1000)

In [32]:
from sklearn.decomposition import TruncatedSVD
svd_model = TruncatedSVD(n_components=20, algorithm='randomized', n_iter=100, random_state=122)
svd_model.fit(X)
len(svd_model.components_)

20

In [33]:
np.shape(svd_model.components_)

(20, 1000)

In [36]:
terms = vectorizer.get_feature_names()

def get_tophics(components, feature_names, n = 5):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [(feature_names[i], topic[i].round(5)) for i in topic.argsort()[:-n-n:-1]])
get_tophics(svd_model.components_, terms)

Topic 1: [('like', 0.21349), ('know', 0.20003), ('people', 0.19229), ('think', 0.17717), ('good', 0.15105), ('time', 0.1442), ('thanks', 0.11571), ('make', 0.10872), ('right', 0.10705)]
Topic 2: [('thanks', 0.32447), ('windows', 0.29158), ('card', 0.18155), ('drive', 0.17559), ('mail', 0.15051), ('file', 0.14701), ('advance', 0.12446), ('files', 0.11542), ('software', 0.11396)]
Topic 3: [('game', 0.37087), ('team', 0.32504), ('year', 0.27875), ('games', 0.25403), ('season', 0.18456), ('players', 0.1612), ('good', 0.15675), ('play', 0.15052), ('hockey', 0.13889)]
Topic 4: [('drive', 0.54434), ('scsi', 0.20589), ('hard', 0.15932), ('disk', 0.15681), ('drives', 0.14049), ('card', 0.13883), ('problem', 0.10705), ('controller', 0.10447), ('floppy', 0.09785)]
Topic 5: [('windows', 0.40336), ('file', 0.25349), ('window', 0.18013), ('files', 0.15978), ('program', 0.13701), ('using', 0.12711), ('problem', 0.10428), ('running', 0.09066), ('version', 0.08801)]
Topic 6: [('government', 0.16049), (

<function get_tophics at 0x00000281AA53C8B0>
