In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [2]:
# 임의의 입력
# 벡터의 차원은 5이고, 문장의 길이가 4인 경우를 가정
# 다시 말해, 4번의 시점이 존재하고, 각 시점마다 5차원의 단어 벡터가 입력으로 사용
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X))

(4, 5)


In [3]:
# RNN은 3D 텐서를 입력받으므로, 3D 텐서로 변경 (배치 크기에 1을 추가)
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [4]:
rnn = SimpleRNN(3)
# rnn = SimpleRNN(3, return_sequences=False, return_state=False와 동일)
hidden_state = rnn(train_X)

print('hidden state : {}, shape : {}'.format(hidden_state, hidden_state.shape))
# 마지막 시점의 은닉 상태, 은닉 상태 크기를 3으로 지정

hidden state : [[-0.9685279  -0.83854824 -0.69189286]], shape : (1, 3)


In [5]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_state = rnn(train_X)

print('hidden state : {}, shape : {}'.format(hidden_state, hidden_state.shape))
# 모든 시점에 대해서 은닉 상태의 값을 출력 (1,4,5)

hidden state : [[[-0.9877675   0.90512323  0.98374325]
  [-0.919358    0.96823525  0.17077407]
  [-0.8220734  -0.70864916  0.14554998]
  [-0.67721677  0.9548978   0.5345618 ]]], shape : (1, 4, 3)


In [6]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

# return_state=True : return_sequences의 True/False 여부와 상관없이 마지막 시점의 은닉 상태를 출력
# 모두 True일 경우, 두 개의 출력을 리턴

hidden states : [[[-0.83891934 -0.99990976  0.9840032 ]
  [-0.1982396  -0.9984261   0.7437964 ]
  [ 0.8230254  -0.9833389   0.8579292 ]
  [ 0.59001464 -0.8311286   0.3606314 ]]], shape: (1, 4, 3)
last hidden state : [[ 0.59001464 -0.8311286   0.3606314 ]], shape: (1, 3)


In [7]:
# return_sequences는 Flase이고, retrun_state가 True일 경우
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

# 두 개의 출력 모두 마지막 시점의 은닉 상태를 출력

hidden states : [[ 0.54062265 -0.99694103  0.9733925 ]], shape: (1, 3)
last hidden state : [[ 0.54062265 -0.99694103  0.9733925 ]], shape: (1, 3)


In [8]:
# LSTM

In [15]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))


hidden state : [[-0.11321384  0.12106262  0.0489713 ]], shape: (1, 3)
last hidden state : [[-0.11321384  0.12106262  0.0489713 ]], shape: (1, 3)
last cell state : [[-0.1799595   0.16626939  0.2062692 ]], shape: (1, 3)


In [10]:
# Bidirectional(LSTM), 양방향 LSTM

In [11]:
# return_sequences가 True인 경우와 False인 경우에 대해서 은닉 상태 값을 확인 위해, 은닉 상태의 값을 고정

k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

In [14]:
# return_sequences가 False, return_state가 True

bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True, \
                           kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backword_h, backword_c = bilstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backword_h, backword_h.shape))


hidden states : [[0.6303139  0.6303139  0.6303139  0.70387346 0.70387346 0.70387346]], shape: (1, 6)
forward state : [[0.6303139 0.6303139 0.6303139]], shape: (1, 3)
backward state : [[0.70387346 0.70387346 0.70387346]], shape: (1, 3)


In [16]:
# return_sequences가 True, return_state가 True

bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True, \
                           kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backword_h, backword_c = bilstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backword_h, backword_h.shape))

hidden states : [[[0.35906476 0.35906476 0.35906476 0.70387346 0.70387346 0.70387346]
  [0.5511133  0.5511133  0.5511133  0.5886358  0.5886358  0.5886358 ]
  [0.5911575  0.5911575  0.5911575  0.39516988 0.39516988 0.39516988]
  [0.6303139  0.6303139  0.6303139  0.2194224  0.2194224  0.2194224 ]]], shape: (1, 4, 6)
forward state : [[0.6303139 0.6303139 0.6303139]], shape: (1, 3)
backward state : [[0.70387346 0.70387346 0.70387346]], shape: (1, 3)
