In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [4]:
# 임의의 입력
# 벡터의 차원은 5이고, 문장의 길이가 4인 경우를 가정
# 다시 말해, 4번의 시점이 존재하고, 각 시점마다 5차원의 단어 벡터가 입력으로 사용
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X))

(4, 5)


In [5]:
# RNN은 3D 텐서를 입력받으므로, 3D 텐서로 변경 (배치 크기에 1을 추가)
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [6]:
rnn = SimpleRNN(3)
# rnn = SimpleRNN(3, return_sequences=False, return_state=False와 동일)
hidden_state = rnn(train_X)

print('hidden state : {}, shape : {}'.format(hidden_state, hidden_state.shape))
# 마지막 시점의 은닉 상태, 은닉 상태 크기를 3으로 지정

hidden state : [[-0.84310573 -0.93992496 -0.76672333]], shape : (1, 3)


In [7]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_state = rnn(train_X)

print('hidden state : {}, shape : {}'.format(hidden_state, hidden_state.shape))
# 모든 시점에 대해서 은닉 상태의 값을 출력 (1,4,5)

hidden state : [[[-0.9864342  -0.3454145  -0.99556786]
  [ 0.43342847 -0.988378   -0.9981795 ]
  [-0.09732466 -0.9902689  -0.99415696]
  [-0.00531618 -0.99335194 -0.78632253]]], shape : (1, 4, 3)


In [8]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

# return_state=True : return_sequences의 True/False 여부와 상관없이 마지막 시점의 은닉 상태를 출력
# 모두 True일 경우, 두 개의 출력을 리턴

hidden states : [[[-0.9947628  -0.997426   -0.9999957 ]
  [-0.9974513  -0.99908996 -0.99999785]
  [-0.9216336  -0.9529649  -0.99996394]
  [-0.9076951   0.1049516  -0.99993443]]], shape: (1, 4, 3)
last hidden state : [[-0.9076951   0.1049516  -0.99993443]], shape: (1, 3)


In [9]:
# return_sequences는 Flase이고, retrun_state가 True일 경우
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

# 두 개의 출력 모두 마지막 시점의 은닉 상태를 출력

hidden states : [[-0.3274632 -0.9558469  0.7028626]], shape: (1, 3)
last hidden state : [[-0.3274632 -0.9558469  0.7028626]], shape: (1, 3)


In [10]:
# LSTM

In [ ]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))